name: heart-data
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.13
  - pip
  - pip:
    - pandas
    - matplotlib
    - pre-commit
    - ruff
    - ipykernel
    - openpyxl
    - pytest
    - jupyter
    - tqdm
    - --editable .
