questionnaire_first = {
    "1": "Have you ever visited the demo site?",
    "2": "How do you usually get to the demo site?",
    "3": "How long does it take to get to the demo site?",
    "4": "When do you usually visit the demo site?",
    "5.1": "How often do you usually visit the demo site? -- Winter",
    "5.2": "How often do you usually visit the demo site? -- Spring",
    "5.3": "How often do you usually visit the demo site? -- Summer",
    "5.4": "How often do you usually visit the demo site? -- Automn",
    "6.1": "What time during the day do you usually visit the demo site? -- Winter",
    "6.2": "What time during the day do you usually visit the demo site? -- Spring",
    "6.3": "What time during the day do you usually visit the demo site? -- Summer",
    "6.4": "What time during the day do you usually visit the demo site? -- Automn",
    "7": "What do you usally do during the visits to the demo site?",
    "8.1": "I am very attached to the demo site",
    "8.2": "The demo site is very special to me",
    "8.3": "I identify strongly with the demo site",
    "8.4": "The demo site is the best place for the activities I like to do",
    "8.5": "No other place can compare to the demo site",
    "8.6": "I would not substitute any other area for the activities I do at the demo site",
    "9.1": "People in the area of the demos site would do something if a house was being broken into",
    "9.2": "In the area of the demo site people would stop children if they saw them vandalizing things",
    "9.3": "People would be affraid to walk alone after dark",
    "9.4": "People in the are of the demo site will treat you unfairly for their own benefit",
    "9.5": "If you were in trouble, there are lots of people in the area of the demo site who would help you",
    "9.6": "Most people in the area of the demo site can be trusted",
    "10.1": "Accessible for people like you",
    "10.2": "Accessible for children",
    "10.3": "Accessible for teenage girls",
    "10.4": "Accessible for teenage boys",
    "10.5": "Accessible for elderly people",
    "10.6": "Accessible for people from cultural/ethnic minorities",
    "10.7": "Accessible for people from LGBTQ+ community",
    "10.8": "Accessible for people with disabilities",
    "10.9": "Accessible for people with low income",
    "11.1": "Safe for people like you",
    "11.2": "Safe for children",
    "11.3": "Safe for teenage girls",
    "11.4": "Safe for teenage boys",
    "11.5": "Safe for elderly people",
    "11.6": "Safe for people from cultural/ethnic minorities",
    "11.7": "Safe for people from LGBTQ+ community",
    "11.8": "Safe for people with disabilities",
    "11.9": "Safe for people with low income",
    "12.1": "Friendly for people like you",
    "12.2": "Friendly for children",
    "12.3": "Friendly for teenage girls",
    "12.4": "Friendly for teenage boys",
    "12.5": "Friendly for elderly people",
    "12.6": "Friendly for people from cultural/ethnic minorities",
    "12.7": "Friendly for people from LGBTQ+ community",
    "12.8": "Friendly for people with disabilities",
    "12.9": "Friendly for people with low income",
    "13.1": "Attractive for people like you",
    "13.2": "Attractive for children",
    "13.3": "Attractive for teenage girls",
    "13.4": "Attractive for teenage boys",
    "13.5": "Attractive for elderly people",
    "13.6": "Attractive for people from cultural/ethnic minorities",
    "13.7": "Attractive for people from LGBTQ+ community",
    "13.8": "Attractive for people with disabilities",
    "13.9": "Attractive for people with low income",
    "14": "Quality of experience",
    "15.1": "In most ways my life is close to my ideal",
    "15.2": "The conditions of my life are excellent",
    "15.3": "I am satisfied with my life",
    "15.4": "So far I have gotten the important things I want in life",
    "15.5": "If I could live my life over, I would change almost nothing",
    "16.1": "I've been feeling optimistic about the future",
    "16.2": "I've been feeling useful",
    "16.3": "I've been feeling relaxed",
    "16.4": "I've been dealing with problems well",
    "16.5": "I've been thinking clearly",
    "16.6": "I've been feeling close to other people",
    "16.7": "I've been able to make up my own mind about things",
    "17.1": "How often do you feel that you lack companionship?",
    "17.2": "How often do you feel left out?",
    "17.3": "How often do you feel isolated from other people?",
    "18": "Age",
    "19": "Sex",
    "20": "Gender",
    "21": "Martial status",
    "22": "Education level",
    "23": "Occupation",
    "24": "What is the number of members of your household?",
    "25": "What is the number of people under 18 in your household?",
    "26": "How many children under 5 you have?",
    "27": "What is the number of members of your household contributing to the household budget?",
    "28": "What is the average total income of your household?",
    "29": "Are you a member of any of the following groups below?",
    "30": "Which religious group do you belong to?",
    "31": "Do you have access in your neighbourghood to the following services?",
    "32": "Did you have any major life change in the last three months?",
    "33": "How many outpatient visit did you have in the past three months due to the disease you are enrolled in this survey?",
    "34": "How many outpatient visits did you have in the past three months due ot any other disease, different from the disease you are enrolled in this survey?",
    "35": "How many days of hospitalization did you have in the past three motnsh due to disease you are enrolled in this survey?",
    "36": "How many days of hospitalization did you hav ein the past three months due to disases, different from the disease you are enrolled in this survey?",
    "37": "How many sick days in total did you take in the past three months due to disease you are enrolled in this survey?",
    "38": "How many sick days in total did you take in the past three months due to disease, different from the disease you are enrolled in this survey?",
    "39": "During the last 7 days, on how many days did you do vigorous physical activities like heavy lifting, digging, aerobics, or fast bicycling?",
    "40": "How much time did you usually spend doing vigorous physical acitivities on one of those days?",
    "41": "During the last 7 days, on how many days did you do moderate physical activities like heavy lifting, digging, aerobics, or fast bicycling?",
    "42": "How much time did you usually spend doing moderate physical acitivities on one of those days?",
    "43": "During the last 7 days, on how many days did you walk for at least 10 min at a time?",
    "44": "How much time did you usually spend walking on one of those days?",
    "45": "During the last 7 days, how much time did you spend sitting on a week day?",
    "46": "When you are working, which of the following best describes what you do?",
    "47": "Do you smoke tabacco?",
    "48": "Have you ever smoked tabacco?",
    "49": "For how many years have smoked daily?",
    "50": "How often did you drink beer, wine, spirits or any other alcoholic beverage, even in small amounts in the past 12 months?",
    "51": "From Monday to Thursday, how many drinks do you have on average on such a day when you drink alcohol?",
    "52.1": "How often do you eat? Red meat",
    "52.2": "How often do you eat? White meat",
    "52.3": "How often do you eat? Fish and sea food",
    "52.4": "How often do you eat? Processed meat",
    "52.5": "How often do you eat? Milk and/or dairy products",
    "52.6": "How often do you eat? Fruits (including frozen, canned and other fruit)",
    "52.7": "How often do you eat? Vegetables (excluding potatos)",
    "52.8": "How often do you eat? Sweets (including cakes, candies, chocolate, pudding, etc.)",
    "52.9": "How often do you eat? Sweetened non-alcoholic beverages (e.g., coca-cola, ice-tea, etc.)",
    "52.10": "How often do you eat? Fast food (e.g., pizza, hamburgers, french fries, any national fast food)",
    "52.11": "How often do you eat? White bread",
    "52.12": "How often do you eat? Wholegrain bread",
    "53": "What kind of fat do you usually use for food preparation?",
    "54": "Do you usually add salt to food you eat, even though the salt was used during the preparation?",
    "55.1": "I found it hard to wind down",
    "55.2": "I was aware of dryness of my mouth",
    "55.3": "I couldn't seem to experiene any positive feeling at all",
    "55.4": "I experienced breathing difficulty",
    "55.5": "I found it difficult to work up the inititative to do things",
    "55.6": "I tended to overreact to situations",
    "55.7": "I experienced trembling",
    "55.8": "I felt I was using a lot of nervous energy",
    "55.9": "I found myself in situations that made me so anxious I was most relived when they ended",
    "55.10": "I felt I that I had nothing to look forward to",
    "55.11": "I felt myself getting agitated",
    "55.12": "I found it difficult to relax",
    "55.13": "I felt down-hearted and blue",
    "55.14": "I was intolerant of anything that kept me from getting on with what I was doing",
    "55.15": "I felt I was close to panic",
    "55.16": "I was unable to become enthusiastic about anything",
    "55.17": "I felt I wan't worth much as a person",
    "55.18": "I felt I was rather touchy",
    "55.19": "I was aware of the action of my heart in the absence of physical exertion",
    "55.20": "I felt scared without any good reason",
    "55.21": "I felt life wasn't worthwhile",
    "56.1": "Indicate the extent you have felt this way over the past week. Interested",
    "56.2": "Indicate the extent you have felt this way over the past week. Distressed",
    "56.3": "Indicate the extent you have felt this way over the past week. Excieted",
    "56.4": "Indicate the extent you have felt this way over the past week. Upset",
    "56.5": "Indicate the extent you have felt this way over the past week. Strong",
    "56.6": "Indicate the extent you have felt this way over the past week. Guilty",
    "56.7": "Indicate the extent you have felt this way over the past week. Scared",
    "56.8": "Indicate the extent you have felt this way over the past week. Hostile",
    "56.9": "Indicate the extent you have felt this way over the past week. Enthusiastic",
    "56.10": "Indicate the extent you have felt this way over the past week. Proud",
    "56.11": "Indicate the extent you have felt this way over the past week. Irritable",
    "56.12": "Indicate the extent you have felt this way over the past week. Alert",
    "56.13": "Indicate the extent you have felt this way over the past week. Ashamed",
    "56.14": "Indicate the extent you have felt this way over the past week. Inspired",
    "56.15": "Indicate the extent you have felt this way over the past week. Nervous",
    "56.16": "Indicate the extent you have felt this way over the past week. Determined",
    "56.17": "Indicate the extent you have felt this way over the past week. Attentive",
    "56.18": "Indicate the extent you have felt this way over the past week. Jittery",
    "56.19": "Indicate the extent you have felt this way over the past week. Active",
    "56.20": "Indicate the extent you have felt this way over the past week. Afraid",
}


questionnaire_final = {
    "1": "Have you ever visited the demo site?",
    "2": "How do you usually get to the demo site?",
    "3": "How long does it take to get to the demo site?",
    "4": "When do you usually visit the demo site?",
    "5.1": "How often do you usually visit the demo site? -- Winter",
    "5.2": "How often do you usually visit the demo site? -- Spring",
    "5.3": "How often do you usually visit the demo site? -- Summer",
    "5.4": "How often do you usually visit the demo site? -- Automn",
    "6.1": "What time during the day do you usually visit the demo site? -- Winter",
    "6.2": "What time during the day do you usually visit the demo site? -- Spring",
    "6.3": "What time during the day do you usually visit the demo site? -- Summer",
    "6.4": "What time during the day do you usually visit the demo site? -- Automn",
    "7": "What do you usally do during the visits to the demo site?",
    "8.1": "I am very attached to the demo site",
    "8.2": "The demo site is very special to me",
    "8.3": "I identify strongly with the demo site",
    "8.4": "The demo site is the best place for the activities I like to do",
    "8.5": "No other place can compare to the demo site",
    "8.6": "I would not substitute any other area for the activities I do at the demo site",
    "9.1": "People in the area of the demos site would do something if a house was being broken into",
    "9.2": "In the area of the demo site people would stop children if they saw them vandalizing things",
    "9.3": "People would be affraid to walk alone after dark",
    "9.4": "People in the are of the demo site will treat you unfairly for their own benefit",
    "9.5": "If you were in trouble, there are lots of people in the area of the demo site who would help you",
    "9.6": "Most people in the area of the demo site can be trusted",
    "10.1": "Accessible for people like you",
    "10.2": "Accessible for children",
    "10.3": "Accessible for teenage girls",
    "10.4": "Accessible for teenage boys",
    "10.5": "Accessible for elderly people",
    "10.6": "Accessible for people from cultural/ethnic minorities",
    "10.7": "Accessible for people from LGBTQ+ community",
    "10.8": "Accessible for people with disabilities",
    "10.9": "Accessible for people with low income",
    "11.1": "Safe for people like you",
    "11.2": "Safe for children",
    "11.3": "Safe for teenage girls",
    "11.4": "Safe for teenage boys",
    "11.5": "Safe for elderly people",
    "11.6": "Safe for people from cultural/ethnic minorities",
    "11.7": "Safe for people from LGBTQ+ community",
    "11.8": "Safe for people with disabilities",
    "11.9": "Safe for people with low income",
    "12.1": "Friendly for people like you",
    "12.2": "Friendly for children",
    "12.3": "Friendly for teenage girls",
    "12.4": "Friendly for teenage boys",
    "12.5": "Friendly for elderly people",
    "12.6": "Friendly for people from cultural/ethnic minorities",
    "12.7": "Friendly for people from LGBTQ+ community",
    "12.8": "Friendly for people with disabilities",
    "12.9": "Friendly for people with low income",
    "13.1": "Attractive for people like you",
    "13.2": "Attractive for children",
    "13.3": "Attractive for teenage girls",
    "13.4": "Attractive for teenage boys",
    "13.5": "Attractive for elderly people",
    "13.6": "Attractive for people from cultural/ethnic minorities",
    "13.7": "Attractive for people from LGBTQ+ community",
    "13.8": "Attractive for people with disabilities",
    "13.9": "Attractive for people with low income",
    "14": "Quality of experience",
    "15.1": "In most ways my life is close to my ideal",
    "15.2": "The conditions of my life are excellent",
    "15.3": "I am satisfied with my life",
    "15.4": "So far I have gotten the important things I want in life",
    "15.5": "If I could live my life over, I would change almost nothing",
    "16.1": "I've been feeling optimistic about the future",
    "16.2": "I've been feeling useful",
    "16.3": "I've been feeling relaxed",
    "16.4": "I've been dealing with problems well",
    "16.5": "I've been thinking clearly",
    "16.6": "I've been feeling close to other people",
    "16.7": "I've been able to make up my own mind about things",
    "17.1": "How often do you feel that you lack companionship?",
    "17.2": "How often do you feel left out?",
    "17.3": "How often do you feel isolated from other people?",
    "18": "Did you have any major life change in the last three months?",
    "19": "How many outpatient visit did you have in the past three months due to the disease you are enrolled in this survey?",
    "20": "How many outpatient visits did you have in the past three months due ot any other disease, different from the disease you are enrolled in this survey?",
    "21": "How many days of hospitalization did you have in the past three motnsh due to disease you are enrolled in this survey?",
    "22": "How many days of hospitalization did you hav ein the past three months due to disases, different from the disease you are enrolled in this survey?",
    "23": "How many sick days in total did you take in the past three months due to disease you are enrolled in this survey?",
    "24": "How many sick days in total did you take in the past three months due to disease, different from the disease you are enrolled in this survey?",
    "25": "During the last 7 days, on how many days did you do vigorous physical activities like heavy lifting, digging, aerobics, or fast bicycling?",
    "26": "How much time did you usually spend doing vigorous physical acitivities on one of those days?",
    "27": "During the last 7 days, on how many days did you do moderate physical activities like heavy lifting, digging, aerobics, or fast bicycling?",
    "28": "How much time did you usually spend doing moderate physical acitivities on one of those days?",
    "29": "During the last 7 days, on how many days did you walk for at least 10 min at a time?",
    "30": "How much time did you usually spend walking on one of those days?",
    "31": "During the last 7 days, how much time did you spend sitting on a week day?",
    "32": "When you are working, which of the following best describes what you do?",
    "33": "Do you smoke tabacco?",
    "34": "Have you ever smoked tabacco?",
    "35": "For how many years have smoked daily?",
    "36": "How often did you drink beer, wine, spirits or any other alcoholic beverage, even in small amounts in the past 12 months?",
    "37": "From Monday to Thursday, how many drinks do you have on average on such a day when you drink alcohol?",
    "38.1": "How often do you eat? Red meat",
    "38.2": "How often do you eat? White meat",
    "38.3": "How often do you eat? Fish and sea food",
    "38.4": "How often do you eat? Processed meat",
    "38.5": "How often do you eat? Milk and/or dairy products",
    "38.6": "How often do you eat? Fruits (including frozen, canned and other fruit)",
    "38.7": "How often do you eat? Vegetables (excluding potatos)",
    "38.8": "How often do you eat? Sweets (including cakes, candies, chocolate, pudding, etc.)",
    "38.9": "How often do you eat? Sweetened non-alcoholic beverages (e.g., coca-cola, ice-tea, etc.)",
    "38.10": "How often do you eat? Fast food (e.g., pizza, hamburgers, french fries, any national fast food)",
    "38.11": "How often do you eat? White bread",
    "38.12": "How often do you eat? Wholegrain bread",
    "39": "What kind of fat do you usually use for food preparation?",
    "40": "Do you usually add salt to food you eat, even though the salt was used during the preparation?",
    "41.1": "I found it hard to wind down",
    "41.2": "I was aware of dryness of my mouth",
    "41.3": "I couldn't seem to experiene any positive feeling at all",
    "41.4": "I experienced breathing difficulty",
    "41.5": "I found it difficult to work up the inititative to do things",
    "41.6": "I tended to overreact to situations",
    "41.7": "I experienced trembling",
    "41.8": "I felt I was using a lot of nervous energy",
    "41.9": "I found myself in situations that made me so anxious I was most relived when they ended",
    "41.10": "I felt I that I had nothing to look forward to",
    "41.11": "I felt myself getting agitated",
    "41.12": "I found it difficult to relax",
    "41.13": "I felt down-hearted and blue",
    "41.14": "I was intolerant of anything that kept me from getting on with what I was doing",
    "41.15": "I felt I was close to panic",
    "41.16": "I was unable to become enthusiastic about anything",
    "41.17": "I felt I wan't worth much as a person",
    "41.18": "I felt I was rather touchy",
    "41.19": "I was aware of the action of my heart in the absence of physical exertion",
    "41.20": "I felt scared without any good reason",
    "41.21": "I felt life wasn't worthwhile",
    "42.1": "Indicate the extent you have felt this way over the past week. Interested",
    "42.2": "Indicate the extent you have felt this way over the past week. Distressed",
    "42.3": "Indicate the extent you have felt this way over the past week. Excieted",
    "42.4": "Indicate the extent you have felt this way over the past week. Upset",
    "42.5": "Indicate the extent you have felt this way over the past week. Strong",
    "42.6": "Indicate the extent you have felt this way over the past week. Guilty",
    "42.7": "Indicate the extent you have felt this way over the past week. Scared",
    "42.8": "Indicate the extent you have felt this way over the past week. Hostile",
    "42.9": "Indicate the extent you have felt this way over the past week. Enthusiastic",
    "42.10": "Indicate the extent you have felt this way over the past week. Proud",
    "42.11": "Indicate the extent you have felt this way over the past week. Irritable",
    "42.12": "Indicate the extent you have felt this way over the past week. Alert",
    "42.13": "Indicate the extent you have felt this way over the past week. Ashamed",
    "42.14": "Indicate the extent you have felt this way over the past week. Inspired",
    "42.15": "Indicate the extent you have felt this way over the past week. Nervous",
    "42.16": "Indicate the extent you have felt this way over the past week. Determined",
    "42.17": "Indicate the extent you have felt this way over the past week. Attentive",
    "42.18": "Indicate the extent you have felt this way over the past week. Jittery",
    "42.19": "Indicate the extent you have felt this way over the past week. Active",
    "42.20": "Indicate the extent you have felt this way over the past week. Afraid",
}

belgrade_q_dct = {
    "Molimo Vas, da od navedena tri parka odaberete onaj koji ćete kao učesnik u studiji posećivati u naredna tri meseca:": "Please choose the park you are going to visit in the next three months",
    "Da li ste ikada posetili gore odabrani park?": "Have you ever visited the demo site?",
    "Koliko vam obično vremena treba da stignete do gore odabranog parka? Molimo Vas, zaokružite jedan odgovor koji najviše odgovara utrošku vremena da do njega stignete.": "How long does it take to get to the demo site?",
    "U većini aspekata moj život je blizu idealnog.": "In most ways my life is close to my ideal",
    "Moji uslovi života su odlični": "The conditions of my life are excellent",
    "Zadovoljan/na sam svojim životom.": "I am satisfied with my life",
    "Do sada imam sve važne stvari koje sam želeo/la u životu.": "So far I have gotten the important things I want in life",
    "Da mogu da živim svoj život ponovo, ne bih menjao/la skoro ništa.": "If I could live my life over, I would change almost nothing",
    "Molimo Vas da na na osnovu Vašeg iskustva ocenite kvalitet poseta gore navedenom parku na skali od 1 do 7 ocenite. Pod kvalitetom iskustva podrazumevamo Vaš utisak o lepoti i čistoći lokacije, kao i čulni doživljaj": "Quality of experience",
    "Osećam optimizam u pogledu budućnosti": "I've been feeling optimistic about the future",
    "Osećam se korisno": "I've been feeling useful",
    "Osećam se opušteno": "I've been feeling relaxed",
    "Dobro sam rešavao/la probleme": "I've been dealing with problems well",
    "Razmišljao/la sam jasno": "I've been thinking clearly",
    "Osećam bliskost sa drugim ljudima": "I've been feeling close to other people",
    "Uspeo/la sam da odlučim o nekim stvarima": "I've been able to make up my own mind about things",
    "Koliko često osećate da vam nedostaje druženje?": "How often do you feel that you lack companionship?",
    "18.	Koliko imate godina:": "Age",
    "19.	Pol:": "Sex",
    "20.	Kako biste definisali svoj rodni identitet?": "Gender",
    "Da li u vašoj okolini imate pristup sledećim uslugama? Molimo vas, odaberite svaku kojoj imate pristup.": "Do you have access in your neighbourghood to the following services?",
    "Koliko često se osećate napuštenim?": "How often do you feel left out?",
    "Koliko često se osećate izolovanim od drugih?": "How often do you feel isolated from other people?",
    "Crveno meso": "How often do you eat? Red meat",
    "Belo meso": "How often do you eat? Red meat",
    "Riba ili plodovi mora": "How often do you eat? Fish and sea food",
    "Mesne prerađevine": "How often do you eat? Processed meat",
    "Mleko i/ili mlečni proizvodi": "How often do you eat? Milk and/or dairy products",
    "Voće (uključujući smrznuto, konzervirano ili drugo)": "How often do you eat? Fruits (including frozen, canned and other fruit)",
    "Povrće ( izuzimajući krompir)": "How often do you eat? Vegetables (excluding potatos)",
    "Slatkiši (uključujući torte, kolače, bombone, čokoladu, puding, itd.)": "How often do you eat? Sweets (including cakes, candies, chocolate, pudding, etc.)",
    "Zaslađena bezalkoholna pića (npr: coca-cola, ledeni čaj itd.)": "How often do you eat? Sweetened non-alcoholic beverages (e.g., coca-cola, ice-tea, etc.)",
    "Brza hrana (npr. pica, hamburger, pomfrit,)": "How often do you eat? Fast food (e.g. pizza, hamburgers, french fries, any national fast food)",
    "Beli hleb": "How often do you eat? White bread",
    "Hleb od celog zrna": "How often do you eat? Wholegrain bread",
    "Molimo Vas, da od navedena tri parka odaberete onaj koji ste kao učesnik u studiji posećivali u prethodna tri meseca:": "Please choose the park you have visited in the last three months",
    "Ljudi poput Vas": "For people like you",
    "Ljudi sa niskim materijalnim": "For people with low income",
    "Ne bih gore odabrani park menjao/la ni za jedno drugo mesto da se bavim svojim aktivnostima": "I would not substitute any other area for the activities I do at the demo site",
    "Poslednje pitanje se odnosi na vreme koje ste proveli sedeći radnim danima tokom poslednjih sedam dana. Uključite vreme provedeno na poslu, kod kuće, dok radite na kursu i tokom slobodnog vremena. Ovo može uključivati vreme provedeno sedeći za stolom, posećujući prijatelje, čitajući ili sedeći ili ležeći da gledate televiziju.   45.	Tokom poslednjih sedam dana, koliko ste vremena proveli sedeći u nedelji?": "During the last 7 days, how much time did you spend sitting on a week day?",
    "Tinejdžeri": "Teenagers",
    "Stariji ljudi": "Elderly people",
    "Većini ljudi iz okoline gore odabranog parka se može verovati": "Most people in the area of the demo site can be trusted",
    "Deca": "Children",
    "Ljudi se plaše da hodaju po gore odabranom parku kada padne mrak.": "People would be affraid to walk alone after dark",
    "Snažno se identifikujem sa gore odabranim parkom": "I identify strongly with the demo site",
    "Gore odabrani park je najbolje za aktivnosti kojima se bavim.": "The demo site is the best place for the activities I like to do",
    "Ukoliko biste se našli u nevolji, mnogi iz okoline gore odabranog parka bi vam pomogli": "If you were in trouble, there are lots of people in the area of the demo site who would help you",
    "Nijedno mesto se ne može porediti sa gore odabrani park": "No other place can compare to the demo site",
    "Gore odabrani park je vrlo posebno mesto za mene.": "The demo site is very special to me",
    "Vrlo sam vezan/a za gore odabrani park": "I am very attached to the demo site",
    "Pripadnici kulturnih i etničkih manjina": "People from cultural/ethnic minorities",
    "Tinejdžerke": "Teenagers",
    "Ljudi u okolini gore odabranog parka bi Vas tretirali nekorektno radi sopstvene koristi.": "People in the area of the demo site will treat you unfairly for their own benefit",
    "Ljudi u blizini gore odabranog parka bi reagovali ako bi neko pokušao da provali u kuću.": "People in the area of the demo site would do something if a house was being broken into",
    "Ljudi sa niskim materijalnim primanjima": "People with low income",
    "Pripadnici LGBTQ+ zajednice": "People from LGBTQ+ community",
    "Ljudi sa invaliditetom": "People with disabilities",
    "U okolini gore odabranog parka ljudi bi sprečili decu da vandalizuju stvari.": "In the area of the demo site people would stop children if they saw them vandalizing things",
}

athens_q_dct = {
    "Πρώτα θα θέλαμε να σας κάνουμε ερωτήσεις σχετικά με τις επισκέψεις σας στο Πεδίον του Άρεως και τη γενική εμπειρία σας με τον χώρο. Έχετε επισκεφθεί ποτέ το Πεδίον του Άρεως;": "Have you ever visited the demo site?",
    "Πρώτα θα θέλαμε να σας κάνουμε ερωτήσεις σχετικά με τις επισκέψεις σας στο Πεδίον του Άρεως και τη γενική εμπειρία σας με τον χώρο.": "Have you ever visited the demo site?",
    "18.	Ποια είναι η ηλικία σας:": "Age",
    "19.	Ποιο είναι το φύλο σας:": "Sex",
    "20.	Πώς θα περιγράφατε την ταυτότητα φύλου σας; Επιλέξτε μόνο μία απάντηση": "Gender",
    "Αναψυκτικά (μη αλκοολούχα) (πχ coca-cola, κρύο τσάι, κτλ)": "How often do you eat? Sweetened non-alcoholic beverages (e.g., coca-cola, ice-tea, etc.)",
    "Ψωμί ολικής άλεσης": "How often do you eat? Wholegrain bread",
    "Λευκό ψωμί": "How often do you eat? White bread",
    "Fast food (πχ πίτσα, burgers, πατάτες τηγανιτές, σουβλάκια και άλλα τρόφιμα σαν και αυτά)": "How often do you eat? Fast food (e.g. pizza, hamburgers, french fries, any national fast food)",
    "Γλυκά (συμπεριλαμβανομένων των κέικ/τούρτες, καραμέλες, σοκολάτες, πουτίγκες/κρέμες κτλ)": "How often do you eat? Sweets (including cakes, candies, chocolate, pudding, etc.)",
    "Φρούτα (συμπεριλαμβανομένων των κατεψυγμένων, κονσερβοποιημένων και άλλων φρούτων)": "How often do you eat? Fruits (including frozen, canned and other fruit)",
    "Υπάρχει κάποιος περιορισμός υγείας;": "Do you have any health restrictions?",
    "Έχετε αλλεργίες;": "Do you have any allergies?",
    "Λαχανικά (εκτός από πατάτες)": "How often do you eat? Vegetables (excluding potatos)",
    "Έχετε πάθηση του θυρεοειδούς; Γνωρίζετε ποια;": "Do you have a thyroid condition? Do you know which one?",
    "Έχετε στεφανιαία νόσο (πρόβλημα στα αγγεία της καρδιάς);": "Do you have coronary artery disease (problem with the blood vessels of the heart)?",
    "Έχετε δυσκαταποσία, ερυγές, δυσπεψία, πόνο πριν ή μετά το γευμά, αίσθημα καύσου, αίσθημα πληρότητας, ναυτία, εμετό, αίσθημα βύθισης, «κινητικότητα» των σπλάγχνων, βορβορυγμούς, χαλάρωση της κύστης, απώλεια βάρους ή δυσκοιλιότητα;": "Do you have dysphagia, eructation, dyspepsia, pain before or after eating, heartburn, feeling of fullness, nausea, vomiting, feeling of sinking, 'motility' of the viscera, borborygmi, relaxation of the bladder, weight loss or constipation?",
    "Έχετε λεύκη;": "Do you have vitiligo?",
    "Rødt kød": "How often do you eat? Red meat",
    "Υπάρχουν εξωτερικοί παράγοντες που επηρεάζουν το άγχος σας σήμερα;": "Are there external factors affecting your anxiety today?",
    "Πόσο συχνά έχετε ανησυχία, εγρήγορση, αναμονή του χειρότερου ή ευερεθιστότητα;": "How often do you feel anxious, alert, expect the worst or irritable?",
    "Λέμε τη λέξη 'Καρέκλα' και ζητούμε να την επαναλάβει αμέσως ο εξεταζόμενος.": "Say the word 'Chair' and ask the examinee to repeat it immediately.",
    "Ζητήστε του να επαναλάβει τις λέξεις 'παιδί, κλειδί, κλαδί'. Σε ποιο χώρο ή μέρος;": "Ask him to repeat the words 'child, key, branch'. In what space or place?",
    "Fuldkornsbrød": "How often do you eat? Wholegrain bread",
    "Trouble concentrating on things, such as reading the newspaper or watching television?": "Trouble concentrating on things, such as reading the newspaper or watching television?",
    "Έχετε πρόβλημα να εργαστείτε υπερωρία στο επερχόμενο πρόγραμμα;": "Do you have a problem working overtime in the upcoming schedule?",
    "Τι φάρμακα παίρνετε;": "What medications do you take?",
    "Πώς θα χαρακτηρίζατε το επίπεδο άγχους σας αυτή τη στιγμή;": "How would you rate your level of anxiety at this time?",
    "Jeg følte, at jeg ikke havde noget at se frem til": "I felt I that I had nothing to look forward to",
    "Στη γειτονία σας σε ποια από τις παρακάτω υπηρεσίες έχετε πρόσβαση; Μπορείτε να επιλέξετε πολλές από τις παρακάτω επιλογές.": "Do you have access in your neighbourghood to the following services?",
    "Fisk og skaldyr": "How often do you eat? Fish and sea food",
    "Πόσες ώρες υπερωρίας εργαστήκατε σήμερα; _____ ώρες (Σημειώστε 0 εάν δεν κάνατε υπερωρία)": "How many hours of overtime did you work today? _____ hours (Note 0 if you did not do overtime)",
    "Πόσα κιλά;": "How many kilos?",
    "During the last 7 days, on how many days did you do vigorous physical activities like heavy lifting, digging, aerobics, or fast bicycling?": "During the last 7 days, on how many days did you do vigorous physical activities like heavy lifting, digging, aerobics, or fast bicycling?",
    "Τι ημερομηνία έχουμε σήμερα;": "What date do we have today?",
    "Først vil vi gerne stille dig spørgsmål vedrørende dine besøg på MarselisborgCentret og din generelle oplevelse med parken. Har du nogensinde besøgt MarselisborgCentret?": "Have you ever visited the demo site?",
    "Ryger du tobak (Færdigt-fremstillede eller håndrullede cigaretter, cigarer)?": "Do you smoke tabacco?",
    "Είστε σε μονάδα τεχνητού νεφρού;": "Are you on a kidney dialysis unit?",
    "Forarbejdet kød": "How often do you eat? Processed meat",
    "Έχετε αγγειοπάθεια;": "Do you have angiopathy?",
    "Jeg havde en tendens til at overreagere på situationer": "I tended to overreact to situations",
    "Έχετε φοβίες όταν βρίσκεστε στο σκοτάδι, όταν είστε με ξένους ή με μεγάλα ζώα, όταν υπάρχει κίνηση στους δρόμους, πλήθος ή όταν μένετε μόνοι σας;": "Do you have phobias when you are in the dark, when you are with strangers or large animals, when there is traffic on the roads, crowds or when you are alone?",
    "Mælk og/eller mejeriprodukter": "How often do you eat? Milk and/or dairy products",
    "Έχετε καρδιακή ανεπάρκεια;": "Do you have heart failure?",
    "Τι έτος;": "Age",
    "hvidt brød": "How often do you eat? White bread",
    "Grøntsager (undtagen kartofler)": "How often do you eat? Vegetables (excluding potatos)",
    "Καπνίζετε;": "Do you smoke tabacco?",
    "Ζητήστε από τον εξεταζόμενο να προφέρει αντίστροφα τα γράμματα της λέξης 'Πέτρα' (αρτεπ). Πόσα γράμματα απάντησε σωστά;": "Ask the examinee to pronounce the letters of the word 'Stone' (artpe) backwards. How many letters did he answer correctly?",
    "Δηλώστε το φύλο σας:": "Gender",
    "If I could live my life over, I would change almost nothing.": "If I could live my life over, I would change almost nothing.",
    "Poor appetite or overeating?": "Poor appetite or overeating?",
    "Moving or speaking so slowly that other people could have noticed? Or the opposite - being so fidgety or restless that you have been moving around a lot more than usual?": "Moving or speaking so slowly that other people could have noticed? Or the opposite - being so fidgety or restless that you have been moving around a lot more than usual?",
    "Σε ποια χώρα είμαστε;": "What country are we in?",
    "Jeg havde svært ved at slappe af (calm)": "I found it difficult to relax",
    "Thoughts that you would be better off dead, or of hurting yourself in some way?": "Thoughts that you would be better off dead, or of hurting yourself in some way?",
    "Σε ποια γειτονιά είμαστε;": "Which neighborhood are we in?",
    "Έχετε διαβητική νευροπάθεια (μουδιάσματα, κράμπες στα πόδια, παγωμένα πόδια, πόδια που καίνε, αίσθηση ότι σας τρυπούν τα πόδια βελόνες ή αγκάθια, ή σας χτυπάει ρεύμα);": "Do you have diabetic neuropathy (numbness, cramps in the legs, cold feet, burning feet, feeling that needles or thorns prick your feet, or electric shock)?",
    "Έχετε διαβητική νεφροπάθεια (Τα νεφρά σας δε λειτουργούν σωστά);": "Do you have diabetic nephropathy (Your kidneys do not work properly)?",
    "Έχετε κοιλιοκάκη;": "Do you have celiac disease?",
    "Ζητήστε από τον εξεταζόμενο να αφαιρέσει από το 86 7 μονάδες (Σωστή απάντηση 79).": "Ask the examinee to subtract 7 from 86 (Correct answer 79).",
    "Jeg følte, at jeg brugte meget nervøs energi": "I felt I was using a lot of nervous energy",
    "Indtil videre har jeg fået de vigtige ting, jeg vil have i livet.": "So far I have gotten the important things I want in life",
    "Ζητήστε από τον εξεταζόμενο να θυμηθεί τις τρείς λέξεις που προηγουμένως του ζητήσατε να επαναλάβει. Σωστή απάντηση 'Φούστα'.": "Ask the examinee to remember the three words you previously asked him to repeat. Correct answer 'Skirt'.",
    "Στο αυτοκίνητο ενώ είστε σταματημένος (η) για λίγα λεπτά λόγω κίνησης": "At the car while you are stopped for a few minutes due to traffic",
    "Increasing walking opportunities in the neighborhood - network of pedestrian walkways covering an area between residences and businesses/services": "Increasing walking opportunities in the neighborhood - network of pedestrian walkways covering an area between residences and businesses/services",
    "Tænk på den tid, du har brugt på at gå i de sidste 7 dage. Dette inkluderer at gå på arbejdet og i hjemmet, gåture for at komme fra sted til sted og enhver anden gåtur, som du måtte gøre udelukkende for rekreation, sport, motion eller fritid.  43.	I løbet af de sidste 7 dage, hvor mange dage gik du i mindst 10 minutter ad gangen? (dage om ugen)  Ingen gang! Gå til spørgsmål 45": "During the last 7 days, on how many days did you walk for at least 10 minutes at a time?",
    "Έχετε κακή διάθεση ή επίσημη διάγνωση κατάθλιψης;": "Do you have a bad mood or a formal diagnosis of depression?",
    "During the last 7 days, how much time did you spend sitting on a week day?": "During the last 7 days, how much time did you spend sitting on a week day?",
    "Δώστε του ένα κομμάτι λευκό χαρτί και πέστε του: 'πάρτε αυτό το χαρτί με το δεξί σας χέρι, διπλώστε το στη μέση, και ακουμπήστε το στο πάτωμα'. Σωστή πρώτη απάντηση: 'Χαρτί στο δεξί χέρι'.": "Give him a piece of white paper and say: 'take this paper with your right hand, fold it in half, and place it on the floor'. Correct first answer: 'Paper in the right hand'.",
    "Επιλέξτε τους κωδικούς των προτιμώμενων συναδέλφων:": "Select the codes of the preferred colleagues:",
    "Λέμε τη λέξη 'Ποδήλατο' και ζητούμε να την επαναλάβει αμέσως ο εξεταζόμενος.": "Say the word 'Bicycle' and ask the examinee to repeat it immediately.",
    "Δείξτε στον εξεταζόμενο ένα ρολόι χειρός και ρωτήστε 'Τι είναι αυτό;'.": "Show the examinee a wristwatch and ask 'What is this?'.",
    "Τι μέρα έχουμε σήμερα;": "What day do we have today?",
    "Hvor meget tid brugte du normalt på at udføre hårde fysiske aktiviteter på en af de dage? (hvis du for eksempel er aktiv i 90 minutter, så skrives det 1 time og 30 minutter; hvis du er aktiv 30 minutter, så skrives det 0 timer og 30 minutter)": "How much time did you usually spend doing vigorous physical acitivities on one of those days?",
    "Ψάρι/Θαλασσινά": "How often do you eat? Fish and sea food",
    "Βαθμός δύσπνοιας": "Dyspnea grade",
    "Πώς θα αξιολογούσατε το επίπεδο άγχους σας τώρα που ολοκληρώσατε τη βάρδια σας;": "How would you rate your level of anxiety now that you have completed your shift?",
    "Jeg havde svært ved at slappe af": "I found it difficult to relax",
    "Κόκκινο Κρέας": "How often do you eat? Red meat",
    "Όταν διαβάζετε κάτι καθισμένος (η)": "At the time you are reading something sitting",
    "Ζητήστε από τον εξεταζόμενο να θυμηθεί τις τρείς λέξεις που προηγουμένως του ζητήσατε να επαναλάβει. Σωστή απάντηση 'Καρέκλα'.": "Ask the examinee to remember the three words you previously asked him to repeat. Correct answer 'Chair'.",
    "Κάνετε υπογλυκαιμίες;": "Do you have hypoglycemia?",
    "During the last 7 days, on how many days did you do moderate physical activities like carrying light loads, bicycling at a regular pace, or doubles tennis? Do not include walking.": "During the last 7 days, on how many days did you do moderate physical activities like heavy lifting, digging, aerobics, or fast bicycling?",
    " Ποιος;": "Who?",
    "Jeg befandt mig i situationer, der gjorde mig så ængstelig, at jeg var meget lettet, da de var ovre": "I found myself in situations that made me so anxious that I was very relieved when they were over",
    "Δώστε του ένα κομμάτι λευκό χαρτί και πέστε του: 'πάρτε αυτό το χαρτί με το δεξί σας χέρι, διπλώστε το στη μέση, και ακουμπήστε το στο πάτωμα'. Σωστή πρώτη απάντηση: 'Τοποθέτηση χαρτιού στο πάτωμα'.": "Give him a piece of white paper and say: 'take this paper with your right hand, fold it in half, and place it on the floor'. Correct first answer: 'Placement of paper on the floor'.",
    "The conditions of my life are excellent.": "The conditions of my life are excellent.",
    "Έχετε χάσει βάρος τον τελευταίο χρόνο;": "Have you lost weight in the last year?",
    "Έχετε συχνοουρία ή έπειξη προς ούρηση, αμηνόρροια, μηνορραγία, ψυχρότητα, πρόωρη εκσπρερμάτωση, απώλεια της γεννετήριας επιθυμίας ή ανικανότητα;": "Do you have frequent urination or urgency to urinate, amenorrhea, menorrhagia, coldness, premature ejaculation, loss of sexual desire or impotence?",
    "Επεξεργασμένο κρέας": "How often do you eat? Processed meat",
    "Έχετε δυσκολία επέλευσης ύπνου, διακοπτόμενο ύπνο, αίσθημα κόπωσης μετά την αφύπνιση, όνειρα εφιάλτες ή νυχτερινούς τρόμους;": "Do you have difficulty falling asleep, interrupted sleep, feeling tired after waking up, nightmares or night terrors?",
    "Hvilken slags fedtstof bruger du normalt til tilberedning af mad (madlavning, bagning, tilberedning af dessert osv.)?": "Which type of fat do you normally use for cooking (cooking, baking, preparing dessert, etc.)?",
    "Tilsætter du normalt salt til den mad du spiser, selvom der blev brugt salt under tilberedningen?": "Do you normally add salt to the food you eat, even if salt was used during cooking?",
    "Έχετε παραμορφώσεις στα δάκτυλα των ποδιών;": "Do you have deformities in the toes?",
    "Έχετε αυξήσει το βάρος σας τον τελευταίο χρόνο;": "Have you gained weight in the last year?",
    "Τι φάρμακο παίρνετε;": "What medication do you take?",
    "In most ways my life is close to my ideal.": "In most ways my life is close to my ideal.",
    "Λευκό κρέας": "How often do you eat? White meat",
    "Jeg følte at jeg var tæt på at gå i panik": "I felt that I was close to panic",
    "Έχετε ξηροστομία, εξάψεις, ωχρότητα, τάση για εφίδρωση, ίλιγγο, κεφαλαλγία τάσης ή ανόρθωση τριχών;": "Do you have dry mouth, hot flashes, pallor, tendency to sweat, dizziness, tension headache or hair standing up?",
    "Jeg følte ikke, at jeg var meget værd som person": "I did not feel that I was worth much as a person",
    "Έχετε εμβοές, θόλωση της όρασης, ψυχρές-θερμές εξάψεις, αίσθημα αδυναμίας ή μουδιάσματα;": "Do you have tinnitus, blurred vision, cold-hot flashes, feeling of weakness or numbness?",
    "Jeg følte, at livet ikke var umagen værd": "I felt that life was not worth the effort",
    "Feeling tired or having little energy?": "Feeling tired or having little energy?",
    "Πόσες ώρες εργαστήκατε σήμερα εάν ήταν αργία; _____ ώρες (Σημειώστε 0 εάν δεν ήταν αργία)": "How many hours did you work today if it was a holiday? _____ hours (Note 0 if it was not a holiday)",
    "So far I have gotten the important things I want in life.": "So far I have gotten the important things I want in life.",
    "Jeg var opmærksom på tørhed i min mund": "I was aware of dryness in my mouth",
    "Φοράτε αντλία συνεχούς έγχυσης ινσουλίνης;": "Do you wear a continuous insulin infusion pump?",
    "Χρειάστηκε να εργαστείτε με λιγότερο προσωπικό από το κανονικό;": "Did you have to work with less staff than usual?",
    "Έχετε απώλεια ενδιαφερόντων, έλλειψη ικανοποίησης από τα χόμπυ σας, κατάθλιψη, πολύ πρωινή αφύπνιση ή διακύμανση διάθεσης κατά τη διάρκεια της ημέρας;": "Do you have loss of interest, lack of satisfaction from your hobbies, depression, very early awakening or mood swings during the day?",
    "Δείξτε του μια κάρτα που γράφει 'Κλείστε του τα μάτια' και πέστε του να κάνει αυτό που λέει. Σωστή θεωρούμε την απάνατηση, μόνο όταν ο εξεταζόμενος κλείσει τα μάτια του.": "Show him a card that says 'Close your eyes' and tell him to do what it says. We consider the answer correct only when the examinee closes his eyes.",
    "Φοράτε αισθητήρα συνεχούς καταγραφής ινσουλίνης;": "Do you wear a continuous insulin recording sensor?",
    "Feeling down, depressed, or hopeless?": "Feeling down, depressed, or hopeless?",
    "Αν ξαπλώσετε το απόγευμα για να ξεκουραστείτε.": "Lie down in the afternoon to rest.",
    "Γάλα / Γαλακτοκομικά προϊόντα": "How often do you eat? Milk and/or dairy products",
    "Ζητάμε να αντιγράψει ένα σχήμα που του δείχνουμε.": "Ask him to copy a shape we show him.",
    "Έχετε αίσθημα πίεσης ή σύσφιξης στο θώρακα, αίσθημα πνιγμού, αναστεναγμούς ή δύσπνοια;": "Do you have a feeling of pressure or tightness in the chest, feeling of suffocation, sighs or shortness of breath?",
    "Αισθάνεστε ένταση, εύκολη κόπωση, αδυναμία χαλάρωσης, έχετε τρομαγμένες αντιδράσεις, εύκολο κλάμμα, τρόμο ή ανησυχία;": "Do you feel tension, easy fatigue, inability to relax, have frightened reactions, easy crying, tremors or anxiety?",
    "Det sidste spørgsmål handler om den tid, du har brugt på at sidde ned i hverdagen i løbet af de sidste 7 dage. Herunder den tid du har brugt på arbejdet, derhjemme, mens du laver kursusarbejde og i fritiden. Dette kan omfatte tid brugt på at sidde ved et skrivebord, besøge venner, læse samt sidde eller ligge ned for at se fjernsyn.  45.	Hvor meget tid brugte du på at sidde på en ugedag i løbet af de sidste 7 dage?": "During the last 7 days, how much time did you spend sitting on a week day?",
    "Έχετε ταχυκαρδία, αίσθημα προκάρδιων παλμών, θωρακικό άλγος, παλλόμενη σφύξη αγγείων, αίσθημα πνιγμού, αναστεναγμούς ή δύσπνοια;": "Do you have tachycardia, feeling of precordial palpitations, chest pain, throbbing pulse of vessels, feeling of suffocation, sighs or shortness of breath?",
    "Little interest or pleasure in doing things?": "Little interest or pleasure in doing things?",
    "Sødede ikke-alkoholiske drikkevarer (f.eks. Coca-Cola, iste osv.)": "How often do you eat? Sweetened non-alcoholic drinks (e.g. Coca-Cola, iced tea, etc.)",
    "During the last 7 days, on how many days did you walk for at least 10 minutes": "During the last 7 days, on how many days did you walk for at least 10 minutes",
    "I am satisfied with my life.": "I am satisfied with my life.",
    "Είχατε ατυχήματα;": "Did you have accidents?",
    "How much time did you usually spend walking on one of those days?": "How much time did you usually spend walking on one of those days?",
    "Jeg oplevede åndedrætsbesvær": "I experienced breathing difficulties",
    "Mit livs vilkår er fremragende.": "My life's conditions are excellent.",
    "Jeg er tilfreds med mit liv.": "I am satisfied with my life.",
    "Δώστε του ένα κομμάτι λευκό χαρτί και πέστε του: 'πάρτε αυτό το χαρτί με το δεξί σας χέρι, διπλώστε το στη μέση, και ακουμπήστε το στο πάτωμα'. Σωστή δεύτερη απάντηση: 'Δίπλωμα χαρτιού στη μέση'.": "Give him a piece of white paper and say: 'take this paper with your right hand, fold it in half, and place it on the floor'. Correct second answer: 'Fold the paper in half'.",
    "Συμπληρώστε τα έτη προϋπηρεσίας σας: _____ έτη": "Fill in your years of experience: _____ years",
    "Fastfood (f.eks. pizza, hamburgere, pommes frites, enhver national fastfood)": "How often do you eat? Fast food (e.g. pizza, hamburgers, fries, any national fast food)",
    "Υπήρξαν εξωτερικοί παράγοντες που επηρέασαν το άγχος σας κατά τη διάρκεια της βάρδιας;": "Have there been external factors that affected your stress during the shift?",
    "Ζητήστε από τον εξεταζόμενο να αφαιρέσει από το 72 7 μονάδες (Σωστή απάντηση 65).": "Ask the examinee to subtract 7 from 72 (Correct answer 65).",
    "Καθισμένος (η) σε ήσυχο περιβάλλον μετά το μεσημεριανό φαγητό χωρίς να έχετε καταναλώσει αλκοόλ": "Seated in a quiet environment after lunch without having consumed alcohol",
    "Επιλέξτε ενα ή περισσότερα συμπτώματα": "Select one or more symptoms",
    "At home, how much green space (trees, grasses, flowers, etc.) can you see through the following window(s)?": "At home, how much green space (trees, grasses, flowers, etc.) can you see through the following window(s)?",
    "Όταν παρακολουθείτε τηλεόραση": "When you watch TV",
    "Τι μήνα;": "Month",
    "Ημερομηνία διάγνωσης διαβήτη": "Date of diabetes diagnosis",
    "Έχετε δυσκολία συγκέντρωσης ή διαταραχές της μνήμης;": "Do you have difficulty concentrating or memory disturbances?",
    "Παίρνετε φάρμακα για άλλες παθήσεις; Προσδιορίστε ποιά:": "Do you take medications for other conditions? Specify which ones:",
    "Jeg følte mig nedslået og nedtrykt": "I felt down-hearted and blue",
    "Ζητήστε από τον εξεταζόμενο να αφαιρέσει από το 100 7 μονάδες (Σωστή απάντηση 93).": "Ask the examinee to subtract 7 from 100 (Correct answer 93).",
    "Επιλέξτε την προτιμώμενη βάρδια για το επερχόμενο πρόγραμμα:": "Select the preferred shift for the upcoming schedule:",
    "Jeg var intolerant over for alt, der afholdt mig fra at komme videre med det, jeg lavede": "I was intolerant of everything that kept me from moving on with what I was doing",
    "Trouble falling or staying asleep, or sleeping too much?": "Trouble falling or staying asleep, or sleeping too much?",
    "Έχετε θυρεοειδοπάθεια Hashimoto (αυτοάνοση θυρεοειδίτιδα);": "Do you have Hashimoto's thyroiditis (autoimmune thyroiditis)?",
    "Hvis jeg kunne leve mit liv om, ville jeg næsten ikke ændre noget.": "If I could live my life over, I would hardly change anything.",
    "Sødesager (inklusiv kager, slik, chokolade, budding osv.)": "How often do you eat? Sweets (including cakes, candy, chocolate, pudding, etc.)",
    "Έχετε ουλίτιδα περιοδοντίτιδα;": "Do you have gingivitis or periodontitis?",
    "Jeg følte mig bange uden nogen god grund": "I felt scared for no good reason",
    "Όταν μιλάτε σε κάποιον καθισμένος (η).": "When you talk to someone sitting",
    "Frugt (inklusiv frossen, dåse og anden frugt)": "How often do you eat? Fruit (including frozen, canned and other fruit)",
    "Έχετε διαβητική αμφιβληστροειδοπάθεια;": "Do you have diabetic retinopathy?",
    "Συμπληρώστε την ηλικία σας: _____ ετών": "Age",
    "På de fleste måder er mit liv tæt på mit ideal.": "In most ways my life is close to my ideal.",
    "Designating public areas as non-smoking zones": "Designating public areas as non-smoking zones",
    "Επιλέξτε το τμήμα σας:": "Select your department:",
    "Ως επιβάτης σε αυτοκίνητο για μια ώρα χωρίς στάση.": "As a passenger in a car for an hour without stopping.",
    "Jeg kunne slet ikke opleve nogen positiv følelse": "I could not experience any positive feeling at all",
    "Jeg var ikke i stand til at blive begejstret for noget som helst": "I was not able to get excited about anything at all",
    "Ακολουθείτε κάποια δίαιτα;": "Are you following any diet?",
    "Έχετε υψηλή χοληστερόλη;": "Do you have high cholesterol?",
    "Υπήρξε κάποια αλλαγή στο προγραμματισμένο πρόγραμμα της βάρδιας σας;": "Was there any change in your scheduled shift?",
    "Είχε κάποιος συγγενής σας διαβήτη;": "Did any of your relatives have diabetes?",
    "Tænk på alle de moderate fysiske aktiviteter, du har lavet i de sidste 7 dage. Moderate fysiske aktiviteter refererer til aktiviteter, der kræver moderat fysisk anstrengelse og får dig til at trække vejret lidt hårdere end normalt. Tænk kun på de fysiske aktiviteter, som du lavede i mindst 10 minutter ad gangen.  41.	Hvor mange dage har du i løbet af de sidste 7 dage dyrket moderate fysiske aktiviteter som lette løft, cykle i almindeligt tempo eller double tennis? Inkluder ikke gåture. (dage om ugen)  Ingen moderat fysisk aktivitet! Gå til spørgsmål 43": "How many days have you done moderate physical activities such as light lifting, cycling at a regular pace or doubles tennis? Do not include walking.",
    "Ζητάμε να γράψει, αυθόρμητα, μια πρόταση. Η πρόταση θεωρείται σωστή, όταν έχει ρήμα και υποκείμενο και είναι κατανοητή.": "Ask him to write a sentence spontaneously. The sentence is considered correct when it has a verb and a subject and is understandable.",
    "Τι εποχή έχουμε τώρα;": "What season do we have now?",
    "Δηλώστε τον ρόλο σας:": "State your role:",
    "Όταν κάθεστε σε δημόσιο χώρο αδρανής (θέατρο, σινεμά, συγκέντρωση).": "When you sit in a public space inactive (theater, cinema, gathering).",
    "Ζητήστε από τον εξεταζόμενο να αφαιρέσει από το 79 7 μονάδες (Σωστή απάντηση 72).": "Ask the examinee to subtract 7 from 79 (Correct answer 72).",
    "Jeg følte, at jeg var ret følsom": "I felt I was rather touchy",
    "Ποια είναι η θρησκεία σας;": "Which religious group do you belong to?",
    "Λέμε τη λέξη 'Φούστα' και ζητούμε να την επαναλάβει αμέσως ο εξεταζόμενος.": "Say the word 'Skirt' and ask the examinee to repeat it immediately.",
    "Jeg havde svært ved at oparbejde initiativet til at gøre ting": "I found it difficult to build up the initiative to do things",
    "Hvidt kød": "How often do you eat? White meat",
    "Ζητήστε από τον εξεταζόμενο να αφαιρέσει από το 93 7 μονάδες (Σωστή απάντηση 86).": "Ask the examinee to subtract 7 from 93 (Correct answer 86).",
    "Έχετε πάθει έμφραγμα;": "Have you had a heart attack?",
    "Είχατε επεμβάσεις;": "Did you have surgeries?",
    "Αυτή τη στιγμή, αισθάνεστε ένταση, αδυναμία χαλάρωσης, έχετε ανήσυχη κίνηση των χεριών, σφίξιμο των χεριών, τράβηγμα δακτύλων,τίκς, βηματίζεται, έχετε τρόμο χεριών, συνοφρύωση, το πρόσωπο σας είναι σε ένταση, έχετε αυξημένο μυικό τόνο, αναστενάζεται ή είναι ωχρό το πρόσωπο σας;": "At this moment, do you feel tension, inability to relax, have restless hand movements, hand clenching, finger pulling, tics, pacing, have hand tremors, frowning, your face is tense, you have increased muscle tone, sighing or your face is pale?",
    "Increasing the number, diversity or accessibility public sports facilities": "Increasing the number, diversity or accessibility public sports facilities",
    "Έχετε υπέρταση (υψηλή πίεση αίματος);": "Do you have hypertension (high blood pressure)?",
    "Σε ποια πόλη ή σε ποιο χωριό είμαστε;": "What city or village are we in?",
    "Increasing bicycling opportunities in the neighborhood - network of bicycle paths covering an area between residences and businesses/services": "Increasing bicycling opportunities in the neighborhood - network of bicycle paths covering an area between residences and businesses/services",
    "Ζητήστε από τον εξεταζόμενο να θυμηθεί τις τρείς λέξεις που προηγουμένως του ζητήσατε να επαναλάβει. Σωστή απάντηση 'Ποδήλατο'.": "Ask the examinee to remember the three words you previously asked him to repeat. Correct answer 'Bicycle'.",
    "Jeg oplevede, at jeg blev oprevet": "I felt that I was torn apart",
    "Έχετε μυικούς πόνους, πιασίματα, δυσκαμψία, μυοκλονίες, μυοσπασμούς, τρίξιμο δοντιών ή αστάθεια φωνής;": "Do you have muscle pain, stiffness, myoclonus, myospasms, teeth grinding or voice instability?",
    "Που βρισκόμαστε τώρα; (σπίτι, νοσοκομείο)": "What are we now? (home, hospital)",
    "Jeg var opmærksom på mit hjerteslag i fravær af fysisk anstrengelse": "I was aware of my heartbeat in the absence of physical exertion",
    "Δείξτε στον εξεταζόμενο ένα μολύβι και ρωτήστε 'Τι είναι αυτό;''.": "Show the examinee a pencil and ask 'What is this?'.",
    "Increasing the extent or accessibility of community gardening facilities": "Increasing the extent or accessibility of community gardening facilities",
    "Feeling bad about yourself - or that you are a failure or have let yourself or your family down?": "Feeling bad about yourself - or that you are a failure or have let yourself or your family down?",
    "Jeg oplevede rysten (f.eks.  i hænderne)": "I experienced shaking (e.g. in the hands)",
    "How often (during the day) do you look out through the following window(s)?": "How often (during the day) do you look out through the following window(s)?",
    "How much time did you usually spend doing vigorous physical activities on one": "How much time did you usually spend doing vigorous physical activities on one",
    "Έχετε ρευματοπάθεια;": "Do you have rheumatism?",
    'Δείξτε στον εξεταζόμενο ένα ρολόι χειρός και ρωτήστε "Τι είναι αυτό;".:': "Show the examinee a wristwatch and ask 'What is this?'.",
    'Ζητήστε από τον εξεταζόμενο να προφέρει αντίστροφα τα γράμματα της λέξης "Πέτρα" (αρτεπ). Πόσα γράμματα απάντησε σωστά;:': "Ask the examinee to pronounce the letters of the word 'Stone' (artpe) in reverse. How many letters did he answer correctly?",
    "Δώστε του ένα κομμάτι λευκό χαρτί και πέστε του: 'πάρτε αυτό το χαρτί με το δεξί σας χέρι, διπλώστε το στη μέση, και ακουμπήστε το στο πάτωμα'. Σωστή δεύτερη απάντηση: 'Δίπλωμα χαρτιού στη μέση'.:": "Give him a piece of white paper and say: 'take this paper with your right hand, fold it in half, and place it on the floor'. Correct second answer: 'Fold the paper in half'.",
    "Ζητήστε από τον εξεταζόμενο να θυμηθεί τις τρείς λέξεις που προηγουμένως του ζητήσατε να επαναλάβει. Σωστή απάντηση 'Φούστα'.:": "Ask the examinee to remember the three words you previously asked him to repeat. Correct answer 'Skirt'.",
    "Λέμε τη λέξη 'Καρέκλα' και ζητούμε να την επαναλάβει αμέσως ο εξεταζόμενος.:": "Say the word 'Chair' and ask the examinee to repeat it immediately.",
    "Λέμε τη λέξη 'Φούστα' και ζητούμε να την επαναλάβει αμέσως ο εξεταζόμενος.:": "Say the word 'Skirt' and ask the examinee to repeat it immediately.",
    "Σε ποιο χώρο ή μέρος;:": "In what space or place?",
    "Ζητήστε από τον εξεταζόμενο να θυμηθεί τις τρείς λέξεις που προηγουμένως του ζητήσατε να επαναλάβει. Σωστή απάντηση 'Ποδήλατο'.:": "Ask the examinee to remember the three words you previously asked him to repeat. Correct answer 'Bicycle'.",
    "Δείξτε του μια κάρτα που γράφει 'Κλείστε του τα μάτια' και πέστε του να κάνει αυτό που λέει. Σωστή θεωρούμε την απάνατηση, μόνο όταν ο εξεταζόμενος κλείσει τα μάτια του.:": "Show him a card that says 'Close your eyes' and tell him to do what it says. We consider the answer correct only when the examinee closes his eyes.",
    "Ζητήστε του να επαναλάβει τις λέξεις 'παιδί, κλειδί, κλαδί'.:": "Ask him to repeat the words 'child, key, branch'.",
    "Λέμε τη λέξη 'Ποδήλατο' και ζητούμε να την επαναλάβει αμέσως ο εξεταζόμενος.:": "Say the word 'Bicycle' and ask the examinee to repeat it immediately.",
    "Ζητήστε από τον εξεταζόμενο να θυμηθεί τις τρείς λέξεις που προηγουμένως του ζητήσατε να επαναλάβει. Σωστή απάντηση 'Καρέκλα'.:": "Ask the examinee to remember the three words you previously asked him to repeat. Correct answer 'Chair'.",
    "Δώστε του ένα κομμάτι λευκό χαρτί και πέστε του: 'πάρτε αυτό το χαρτί με το δεξί σας χέρι, διπλώστε το στη μέση, και ακουμπήστε το στο πάτωμα'. Σωστή πρώτη απάντηση: 'Τοποθέτηση χαρτιού στο πάτωμα'.:": "Give him a piece of white paper and say: 'take this paper with your right hand, fold it in half, and place it on the floor'. Correct first answer: 'Paper placement on the floor'.",
    'Δώστε του ένα κομμάτι λευκό χαρτί και πέστε του: "πάρτε αυτό το χαρτί με το δεξί σας χέρι, διπλώστε το στη μέση, και ακουμπήστε το στο πάτωμα". Σωστή πρώτη απάντηση: "Χαρτί στο δεξί χέρι".:': "Give him a piece of white paper and say: 'take this paper with your right hand, fold it in half, and place it on the floor'. Correct first answer: 'Paper in the right hand'.",
    "Δείξτε στον εξεταζόμενο ένα μολύβι και ρωτήστε 'Τι είναι αυτό;'.:": "Show the examinee a pencil and ask 'What is this?'.",
    "Εμπνευσμένοσ": "Indicate the extent you have felt this way over the past week. Inspired",
}

aarhus_q_dct = {
    "Først vil vi gerne stille dig spørgsmål vedrørende dine besøg på MarselisborgCentret og din generelle oplevelse med parken. Har du nogensinde besøgt MarselisborgCentret?": "Have you ever visited the demo site?",
    "Hvad er din alder:": "Age",
    "Hvad er dit køn:": "Sex",
    "Fuldkornsbrød": "How often do you eat? Whole grain bread",
    "Mælk og/eller mejeriprodukter": "How often do you eat? Milk and/or dairy products",
    "Hvad er det højeste uddannelsesniveau, du har gennemført? Vælg venligst kun ét svar.": "What is the highest level of education you have completed? Please select only one answer.",
    "Hvor mange sygedage tog du i alt inden for de seneste tre måneder på grund af den sygdom, der er årsag til at du er tilknyttet denne undersøgelse? (angiv venligst antal sygedage)": "How many sick days did you take in total in the last three months due to the illness that is the reason for your participation in this study? (please specify the number of sick days)",
    "Jeg har følt mig nyttig": "I've been feeling useful",
    "Forarbejdet kød": "How often do you eat? Processed meat",
    "Jeg var opmærksom på mit hjerteslag i fravær af fysisk anstrengelse": "I was aware of my heartbeat in the absence of physical exertion",
    "for teenagepiger": "For teenagers",
    "For børn": "For children",
    "Hvilken religiøs gruppe tilhører du?": "Which religious group do you belong to?",
    "Indtil videre har jeg fået de vigtige ting, jeg vil have i livet.": "So far, I have gotten the important things I want in life.",
    "Hvor mange dage har du været indlagt inden for de seneste tre måneder på grund af den sygdom, der er årsag til at du er tilknyttet denne undersøgelse? (angiv venligst antal dages indlæggelse)": "How many days have you been hospitalized in the last three months due to the illness that is the reason for your participation in this study? (please specify the number of days of hospitalization)",
    "Jeg ville ikke erstatte noget andet område med de aktiviteter, jeg udfører på MarselisborgCentret": "I would not replace any other area with the activities I perform at MarselisborgCentret",
    "Jeg oplevede rysten (f.eks.  i hænderne)": "I experienced shaking (e.g. in the hands)",
    "Hvor mange medlemmer er der i din husstand (inklusive dig)?": "What is the number of members of your household?",
    "For teenagepiger": "For teenagers",
    "Jeg har håndteret problemer godt": "I've been dealing with problems well",
    "Jeg har følt mig tæt på andre mennesker": "I've been feeling close to other people",
    "Jeg kunne slet ikke opleve nogen positiv følelse": "I couldn't seem to experience any positive feeling at all",
    "Jeg følte ikke, at jeg var meget værd som person": "I fel I wasn't worth much as a person",
    "Jeg var ikke i stand til at blive begejstret for noget som helst": "I was unable to become enthusiastic about anything",
    "Hvad tid i løbet af dagen besøger du normalt MarselisborgCentret i de følgende sæsoner? - Sommer": "What time of day do you usually visit MarselisborgCentret in the following seasons? - Summer",
    "For personer med lav indkomst": "For people with low income",
    "Jeg er meget knyttet til MarselisborgCentret": "I am very attached to MarselisborgCentret",
    "Hvor ofte plejer du at besøge MarselisborgCentret i de følgende sæsoner? - Efterår": "How often do you usually visit MarselisborgCentret in the following seasons? - Autumn",
    "Hvor ofte føler du dig isoleret fra andre?": "How often do you feel isolated from others?",
    "Skyldig": "Indicate the extent you have felt this way over the past week. Guilty",
    "Fastfood (f.eks. pizza, hamburgere, pommes frites, enhver national fastfood)": "How often do you eat? Fast food (e.g. pizza, hamburgers, fries, any national fast food)",
    "Hvad er din civilstatus? Vælg venligst kun ét svar.": "Martial status",
    "Jeg har tænkt klart": "I've been thinking clearly",
    "Nervøs": "Indicate the extent you have felt this way over the past week. Nervous",
    "Det sidste spørgsmål handler om den tid, du har brugt på at sidde ned i hverdagen i løbet af de sidste 7 dage. Herunder den tid du har brugt på arbejdet, derhjemme, mens du laver kursusarbejde og i fritiden. Dette kan omfatte tid brugt på at sidde ved et skrivebord, besøge venner, læse samt sidde eller ligge ned for at se fjernsyn.  45.	Hvor meget tid brugte du på at sidde på en ugedag i løbet af de sidste 7 dage?": "During the last 7 days, how much time did you spend sitting on a week day?",
    "Sødesager (inklusiv kager, slik, chokolade, budding osv.)": "How often do you eat? Sweets (including cakes, candy, chocolate, pudding, etc.)",
    "Hvor mange børn under 3 år har du?": "How many children under 5 years do you have?",
    "Jeg er tilfreds med mit liv.": "I am satisfied with my life.",
    "Irritabel": "Indicate the extent you have felt this way over the past week. Irritable",
    "Inspireret": "Indicate the extent you have felt this way over the past week. Inspired",
    "Jeg oplevede åndedrætsbesvær": "I experienced shortness of breath",
    "Mit livs vilkår er fremragende.": "The conditions of my life are excellent.",
    "Jeg oplevede, at jeg blev oprevet": "I felt that I was torn apart",
    "Aktiv": "Indicate the extent you have felt this way over the past week. Active",
    "Jeg var intolerant over for alt, der afholdt mig fra at komme videre med det, jeg lavede": "I was intolerant of anything that kept me from getting on with what I was doing",
    "Skamfuld": "Indicate the extent you have felt this way over the past week. Ashamed",
    "Hvis du var i problemer, er der masser af mennesker MarselisborgCentret, som ville hjælpe dig.": "If you were in trouble, there are lots of people at the demo site who would help you.",
    "Hvor mange medlemmer af din husstand bidrager til husstandens budget (inklusive dig selv)?": "What is the number of members of your household contributing to the household budget?",
    "Jeg befandt mig i situationer, der gjorde mig så ængstelig, at jeg var meget lettet, da de var ovre": "I found myself in situations that made me so anxious that I was most relieved when they ended",
    "Jeg følte, at livet ikke var umagen værd": "I felt that life wasn't worthwhile",
    "Folk ville være bange for at gå alene efter mørkets frembrud.": "People would be afraid to walk alone after dark.",
    "Hvor mange personer under 18 er der i din husstand": "How many people under 18 are there in your household?",
    "Hvor ofte plejer du at besøge MarselisborgCentret i de følgende sæsoner? - Vinter": "How often do you usually visit the demo site in the following seasons? - Winter",
    "Jeg har været i stand til selv at tage beslutninger om ting": "I've been able to make up my own mind about things",
    "Tilsætter du normalt salt til den mad du spiser, selvom der blev brugt salt under tilberedningen?": "Do you usually add salt to the food you eat, even if salt was used during cooking?",
    "Stolt": "Indicate the extent you have felt this way over the past week. Proud",
    "Hvad er den gennemsnitlige samlede indkomst for din husstand?": "What is the average total income of your household?",
    "MarselisborgCentret er det bedste sted for de aktiviteter, jeg kan lide at lave.": "The demo site is the best place for the activities I like to do.",
    "Jeg følte, at jeg ikke havde noget at se frem til": "I felt that I had nothing to look forward to",
    "For  mennesker med handicap": "For people with disabilities",
    "Hvor lang tid tager det dig at komme til MarselisborgCentret?": "How long does it take you to get to the demo site?",
    "Tænk på alle de moderate fysiske aktiviteter, du har lavet i de sidste 7 dage. Moderate fysiske aktiviteter refererer til aktiviteter, der kræver moderat fysisk anstrengelse og får dig til at trække vejret lidt hårdere end normalt. Tænk kun på de fysiske aktiviteter, som du lavede i mindst 10 minutter ad gangen.  41.	Hvor mange dage har du i løbet af de sidste 7 dage dyrket moderate fysiske aktiviteter som lette løft, cykle i almindeligt tempo eller double tennis? Inkluder ikke gåture. (dage om ugen)  Ingen moderat fysisk aktivitet! Gå til spørgsmål 43": "During the last 7 days, how many days have you done moderate physical activities such as light lifting, cycling at a regular pace or doubles tennis? Do not include walking?",
    "MarselisborgCentret er meget specielt for mig": "The demo site is very special to me",
    "Hvad beskriver bedst din nuværende situation? Vælg venligst kun ét svar.": "Occupation",
    "Hvad tid i løbet af dagen besøger du normalt MarselisborgCentret i de følgende sæsoner? - Forår": "What time of day do you usually visit the demo site in the following seasons? - Spring",
    "Jeg følte mig bange uden nogen god grund": "I felt scared for no good reason",
    "Hvor mange ambulante besøg (medicinsk undersøgelse eller behandling som foregår uden indlæggelse på et hospital) har du haft inden for de seneste tre måneder på grund af en anden sygdom, end den der er årsag til at du er tilknyttet denne undersøgelse? (angiv venligst antal ambulante besøg)": "How many outpatient visits (medical examination or treatment that takes place without hospitalization) have you had in the last three months due to an illness other than the one that is the reason for your participation in this study? (please specify the number of outpatient visits)",
    "Ryger du tobak (Færdigt-fremstillede eller håndrullede cigaretter, cigarer)?": "Do you smoke tabacco?",
    "Folk i området for MarselisborgCentret ville gøre noget, hvis et hus blev brudt ind i.": "People in the area around of the demo site would do something if a house was broken into.",
    "I området for MarselisborgCentret ville folk stoppe børn, hvis de så dem ødelægge ting.": "People in the area around the demo site would stop children if they saw them vandalizing things.",
    "Målrettet": "Indicate the extent you have felt this way over the past week. Focused",
    "Hvor mange sygedage tog du i alt inden for de seneste tre måneder på grund af en anden sygdom, end den der er årsag til at du er tilknyttet denne undersøgelse? (angiv venligst antal sygedage)": "How many sick days did you take in total in the last three months due to an illness other than the one that is the reason for your participation in this study? (please specify the number of sick days)",
    "Hvor ofte føler du, at du mangler selskab?": "How often do you feel that you lack companionship?",
    "Rødt kød": "How often do you eat? Red meat",
    "Hvilken slags fedtstof bruger du normalt til tilberedning af mad (madlavning, bagning, tilberedning af dessert osv.)?": "Which type of fat do you usually use for cooking food (cooking, baking, preparing desserts, etc.)?",
    "For personer fra kulturelle/etniske minoriteter": "For people from cultural/ethnic minorities",
    "Spændt": "Indicate the extent you have felt this way over the past week. Tense",
    "Interesseret": "Indicate the extent you have felt this way over the past week. Interested",
    "For ældre": "For elderly people",
    "Jeg havde en tendens til at overreagere på situationer": "I tended to overreact to situations",
    "Jeg følte at jeg var tæt på at gå i panik": "I felt like I was close to panic",
    "De fleste mennesker i MarselisborgCentret kan man stole på.": "Most people at the demo site can be trusted.",
    "Bange (Scared)": "Indicate the extent you have felt this way over the past week. Scared",
    "Hvor ofte plejer du at besøge MarselisborgCentret i de følgende sæsoner? - Forår": "How often do you usually visit the demo site in the following seasons? - Spring",
    "Stærk": "Indicate the extent you have felt this way over the past week. Strong",
    "For personer fra kulturelle/ etniske minoriteter": "For people from cultural/ethnic minorities",
    "På de fleste måder er mit liv tæt på mit ideal.": "In most ways my life is close to my ideal.",
    "Jeg følte, at jeg brugte meget nervøs energi": "I felt that I was using a lot of nervous energy",
    "Jeg havde svært ved at slappe af (calm)": "I found it difficult to relax",
    "For teenagedrenge": "For teenagers",
    "Har du haft nogen større livsændring inden for de sidste tre måneder (f.eks. holde op/begynde at ryge, skifte job eller civilstand, større ulykke, større positiv begivenhed...)": "Have you had any major life changes in the last three months (e.g. quitting/starting smoking, changing jobs or marital status, major accident, major positive event...)",
    "Hvor ofte plejer du at besøge MarselisborgCentret i de følgende sæsoner? - Sommer": "How often do you usually visit the demo site in the following seasons? - Summer",
    "Hvad plejer du at gøre når du besøger MarselisborgCentret? Tag udgangspunkt i den mest almindelige aktivitet.": "What do you usally do during the visits to the demo site?",
    "Hvor mange dage har du været indlagt inden for de seneste tre måneder på grund af en anden sygdom, end den der er årsag til at du er tilknyttet denne undersøgelse? (angiv venligst antal dages indlæggelse)": "How many days have you been hospitalized in the last three months due to an illness other than the one that is the reason for your participation in this study? (please specify the number of days of hospitalization)",
    "Hvor meget tid brugte du normalt på at udføre hårde fysiske aktiviteter på en af de dage? (hvis du for eksempel er aktiv i 90 minutter, så skrives det 1 time og 30 minutter; hvis du er aktiv 30 minutter, så skrives det 0 timer og 30 minutter)": "How much time did you usually spend doing vigorous physical acitivities on one of those days?",
    "Årvågen": "Indicate the extent you have felt this way over the past week. Alert",
    "Anspændt": "Indicate the extent you have felt this way over the past week. Tense",
    "Hvor mange ambulante besøg (medicinsk undersøgelse eller behandling som foregår uden indlæggelse på et hospital) har du haft inden for de seneste tre måneder på grund af den sygdom, der er årsag til at du er tilknyttet denne undersøgelse? (angiv venligst antal ambulante besøg)": "How many outpatient visits (medical examination or treatment that takes place without hospitalization) have you had in the last three months due to the illness that is the reason for your participation in this study? (please specify the number of outpatient visits)",
    "Sødede ikke-alkoholiske drikkevarer (f.eks. Coca-Cola, iste osv.)": "How often do you eat? Sweetened non-alcoholic beverages (e.g., coca-cola, ice-tea, etc.)",
    "hvidt brød": "How often do you eat? White bread",
    "Jeg følte mig nedslået og nedtrykt": "I felt down-hearted and blue",
    "Hvordan vil du beskrive din kønsidentitet? Vælg venligst kun ét svar.": "Gender",
    "Foruroliget": "Indicate the extent you have felt this way over the past week. Upset",
    "Hvad tid i løbet af dagen besøger du normalt MarselisborgCentret i de følgende sæsoner? - Vinter": "What time of day do you usually visit the demo site in the following seasons? - Winter",
    "Bange (Afraid)": "Indicate the extent you have felt this way over the past week. Afraid",
    "Har du adgang til følgende tjenester i dit nabolag? Vælg venligst hver af de listede, som du har adgang til i dit nabolag.": "Do you have access in your neighbourghood to the following services?",
    "Frugt (inklusiv frossen, dåse og anden frugt)": "How often do you eat? Fruit (including frozen, canned and other fruit)",
    "Hvis jeg kunne leve mit liv om, ville jeg næsten ikke ændre noget.": "If I could live my life over, I would change almost nothing.",
    "Jeg havde svært ved at slappe af": "I found it difficult to relax",
    "Jeg identificerer mig stærkt med MarselisborgCentret": "I identify strongly with the demo site",
    "Jeg var opmærksom på tørhed i min mund": "I was aware of dryness in my mouth",
    "Oprevet": "Indicate the extent you have felt this way over the past week. Upset",
    "Jeg har følt mig afslappet": "I've been feeling relaxed",
    "Grøntsager (undtagen kartofler)": "How often do you eat? Vegetables (except potatoes)",
    "Jeg har følt mig optimistisk med hensyn til fremtiden": "I've been feeling optimistic about the future",
    "For mennesker med handicap": "For people with disabilities",
    "Jeg havde svært ved at oparbejde initiativet til at gøre ting": "I found it difficult to work up the inititative to do things",
    "Hvor ofte føler du dig udenfor?": "How often do you feel left out?",
    "Hvornår besøger du normalt MarselisborgCentret?": "When do you usually visit the demo site?",
    "Intet andet sted kan sammenlignes med MarselisborgCentret": "No other place can compare to the demo site",
    "Folk i MarselisborgCentret vil behandle dig uretfærdigt til deres egen fordel.": "People at the demo site will treat you unfairly to their own benefit",
    "Jeg følte, at jeg var ret følsom": "I felt I was rather touchy",
    "Hvad tid i løbet af dagen besøger du normalt MarselisborgCentret i de følgende sæsoner? - Efterår": "What time of day do you usually visit the demo site in the following seasons? - Autumn",
    "Fisk og skaldyr": "How often do you eat? Fish and seafood",
    "Tænk på den tid, du har brugt på at gå i de sidste 7 dage. Dette inkluderer at gå på arbejdet og i hjemmet, gåture for at komme fra sted til sted og enhver anden gåtur, som du måtte gøre udelukkende for rekreation, sport, motion eller fritid.  43.	I løbet af de sidste 7 dage, hvor mange dage gik du i mindst 10 minutter ad gangen? (dage om ugen)  Ingen gang! Gå til spørgsmål 45": "During the last 7 days, how many days did you walk for at least 10 min at a time?",
    "Fjendtlig": "Indicate the extent you have felt this way over the past week. Hostile",
    "For personer fra LGBTQ+-fællesskabet": "For people from the LGBTQ+ community",
    "Bedøm venligst på en skala fra 1 til 7, hvad kvaliteten af din oplevelse på MarselisborgCentret er ifølge din mening. Med kvaliteten af oplevelsen mener vi din opfattelse af æstetik og renhed og sansekomfort oplevet på stedet.": "Quality of experience",
    "Entusiastisk": "Indicate the extent you have felt this way over the past week. Enthusiastic",
    "For dig": "For you",
    "Opmærksom": "Indicate the extent you have felt this way over the past week. Attentive",
    "Hvidt kød": "How often do you eat? White meat",
}
