questions_dct = {
    "1": "Have you ever visited the demo site?",
    "2": "How do you usually get to the demo site?",
    "3": "How long does it take to get to the demo site?",
    "4": "When do you usually visit the demo site?",
    "5.1": "How often do you usually visit the demo site? -- Winter",
    "5.2": "How often do you usually visit the demo site? -- Spring",
    "5.3": "How often do you usually visit the demo site? -- Summer",
    "5.4": "How often do you usually visit the demo site? -- Automn",
    "6.1": "What time during the day do you usually visit the demo site? -- Winter",
    "6.2": "What time during the day do you usually visit the demo site? -- Spring",
    "6.3": "What time during the day do you usually visit the demo site? -- Summer",
    "6.4": "What time during the day do you usually visit the demo site? -- Automn",
    "7": "What do you usally do during the visits to the demo site?",
    "8.1": "I am very attached to the demo site",
    "8.2": "The demo site is very special to me",
    "8.3": "I identify strongly with the demo site",
    "8.4": "The demo site is the best place for the activities I like to do",
    "8.5": "No other place can compare to the demo site",
    "8.6": "I would not substitute any other area for the activities I do at the demo site",
    "9.1": "People in the area of the demos site would do something if a house was being broken into",
    "9.2": "In the area of the demo site people would stop children if they saw them vanalizing things",
    "9.3": "People would be affraid to walk alone after dark",
    "9.4": "People in the are of the demo site will treat you unfairly for their own benefit",
    "9.5": "If you were in trouble, there are lots of people in the area of the demo site who would help you",
    "9.6": "Most people in the area of the demo site can be trusted",
    "10.1": "Accessible for people like you",
    "10.2": "Accessible for children",
    "10.3": "Accessible for teenage girls",
    "10.4": "Accessible for teenage boys",
    "10.5": "Accessible for elderly people",
    "10.6": "Accessible for people from cultural/ethnic minorities",
    "10.7": "Accessible for people from LGBTQ+ community",
    "10.8": "Accessible for people with disabilities",
    "10.9": "Accessible for people with low income",
    "11.1": "Safe for people like you",
    "11.2": "Safe for children",
    "11.3": "Safe for teenage girls",
    "11.4": "Safe for teenage boys",
    "11.5": "Safe for elderly people",
    "11.6": "Safe for people from cultural/ethnic minorities",
    "11.7": "Safe for people from LGBTQ+ community",
    "11.8": "Safe for people with disabilities",
    "11.9": "Safe for people with low income",
    "12.1": "Friendly for people like you",
    "12.2": "Friendly for children",
    "12.3": "Friendly for teenage girls",
    "12.4": "Friendly for teenage boys",
    "12.5": "Friendly for elderly people",
    "12.6": "Friendly for people from cultural/ethnic minorities",
    "12.7": "Friendly for people from LGBTQ+ community",
    "12.8": "Friendly for people with disabilities",
    "12.9": "Friendly for people with low income",
    "13.1": "Attractive for people like you",
    "13.2": "Attractive for children",
    "13.3": "Attractive for teenage girls",
    "13.4": "Attractive for teenage boys",
    "13.5": "Attractive for elderly people",
    "13.6": "Attractive for people from cultural/ethnic minorities",
    "13.7": "Attractive for people from LGBTQ+ community",
    "13.8": "Attractive for people with disabilities",
    "13.9": "Attractive for people with low income",
    "14": "Quality of experience",
    "15.1": "In most ways my life is close to my ideal",
    "15.2": "The conditions of my life are excellent",
    "15.3": "I am satisfied with my life",
    "15.4": "So far I have gotten the important things I want in life",
    "15.5": "If I could live my life over, I would change almost nothing",
    "16.1": "I've been feeling optimistic about the future",
    "16.2": "I've been feeling useful",
    "16.3": "I've been feeling relaxed",
    "16.4": "I've been dealing with problems well",
    "16.5": "I've been thinkign clearly",
    "16.6": "I've been feeling close to other people",
    "16.7": "I've been able to make up my own mind about things",
    "17.1": "How often do you feel that you lack companionship?",
    "17.2": "How often do you feel left out?",
    "17.3": "How often do you feel isolated from other people?",
    ## "18": "Age",
    ## "19": "Sex",
    ## "20": "Gender",
    ## "21": "Martial status",
    ## "22": "Education level",
    ## "23": "Occupation",
    ## "24": "What is the number of members of your household?",
    ## "25": "What is the number of people under 18 in your household?",
    ## "26": "How many children under 5 you have?",
    ## "27": "What is the number of members of your household contributing to the household budget?",
    ## "28": "What is the average total income of your household?",
    ## "29": "Are you a member of any of the following groups below?",
    ## "30": "Which religious group do you belong to?",
    ## "31": "Do you have access in your neighbourghood to the following services?",
    ## "32": "Did you have any major life change in the last three months?",
    ## "33": "How many outpatient visit did you have in the past three months due to the disease you are enrolled in this survey?",
    ## "34": "How many outpatient visits did you have in the past three months due ot any other disease, different from the disease you are enrolled in this survey?",
    ## "35": "How many days of hospitalization did you have in the past three motnsh due to disease you are enrolled in this survey?",
    ## "36": "How many dayis of hospitalization did you hav ein the past three months due to disases, different from the disease you are enrolled in this survey?",
    ## "37": "How many sick days in total did you take in the past three months due to disease you are enrolled in this survey?",
    ## "38": "How many sick days in total did you take in the past three months due to disease, different from the disease you are enrolled in this survey?",
    ## "39": "During the last 7 days, on how many days did you do vigorous physical activities like heavy lifting, digging, aerobics, or fast bicycling?",
    ## "40": "How much time did you usually spend doing vigorous physical acitivities on one of those days?",
    ## "41": "During the last 7 days, on how many days did you do moderate physical activities like heavy lifting, digging, aerobics, or fast bicycling?",
    ## "42": "How much time did you usually spend doing moderate physical acitivities on one of those days?",
    ## "43": "During the last 7 days, on how many days did you walk for at least 10 min at a time?",
    ## "44": "How much time did you usually spend walking on one of those days?",
    ## "45": "During the last 7 days, how much time did you spend sitting on a week day?",
    ## "46": "When you are working, which of the following best describes what you do?",
    ## "47": "Do you smoke tabacco?",
    ## "48": "Have you ever smoked tabacco?",
    ## "49": "For how many years have smoked daily?",
    ## "50": "How often did you dring beer, wine, spirits or any other alcoholic beverage, even in small amounts in the past 12 months?",
    ## "51": "From Monday to Thursday, how many drinks do you have on average on such a day when you drink alcohol?",
    ## "52.1": "How often do you eat? Red meat",
    ## "52.2": "How often do you eat? White meat",
    ## "52.3": "How often do you eat? Fish and sea food",
    ## "52.4": "How often do you eat? Processed meat",
    ## "52.5": "How often do you eat? Milk and/or dairy products",
    ## "52.6": "How often do you eat? Fruits (including frozen, canned and other fruit)",
    ## "52.7": "How often do you eat? Vegetables (excluding potatos)",
    ## "52.8": "How often do you eat? Sweets (including cakes, candies, chocolate, pudding, etc.)",
    ## "52.9": "How often do you eat? Sweetened non-alcoholic beverages (e.g., coca-cola, ice-tea, etc.)",
    ## "52.10": "How often do you eat? Fast food (e.g., pizza, hamburgers, french fries, any national fast food)",
    ## "52.11": "How often do you eat? White bread",
    ## "52.12": "How often do you eat? Wholegrain bread",
    ## "53": "What kind of fat do you usually use for food preparation?",
    ## "54": "Do you usually add salt to food you eat, even though the salt was used during the preparation?",
    ## "55.1": "I found it hard to wind down",
    ## "55.2": "I was aware of dryness of my mouth",
    ## "55.3": "I couldn't seem to experiene any positive feeling at all",
    ## "55.4": "I experienced breathing difficulty",
    ## "55.5": "I found it difficult to work up the inititative to do things",
    ## "55.6": "I tended to overreact to situations",
    ## "55.7": "I experienced trembling",
    ## "55.8": "I felt I was using a lot of nervous energy",
    ## "55.9": "I found myself in situations that made me so anxious I was most relived when they ended",
    ## "55.10": "I felt I that I had nothing to look forward to",
    ## "55.11": "I felt myself getting agitated",
    ## "55.12": "I found it difficult to relax",
    ## "55.13": "I felt down-hearted and blue",
    ## "55.14": "I was intolerant of anything that kept me from getting on with what I was doing",
    ## "55.15": "I felt I was close to panic",
    ## "55.16": "I was unable to become enthusiastic about anything",
    ## "55.17": "I felt I wan't worth much as a person",
    ## "55.18": "I felt I was rather touchy",
    ## "55.19": "I was aware of the action of my heart in the absence of physical exertion",
    ## "55.20": "I felt scared without any good reason",
    ## "55.21": "I felt life wasn't worthwhile",
    ## "56.1": "Indicate the extent you have felt this way over the past week. Interested",
    ## "56.2": "Indicate the extent you have felt this way over the past week. Distressed",
    ## "56.3": "Indicate the extent you have felt this way over the past week. Excieted",
    ## "56.4": "Indicate the extent you have felt this way over the past week. Upset",
    ## "56.5": "Indicate the extent you have felt this way over the past week. Strong",
    ## "56.6": "Indicate the extent you have felt this way over the past week. Guilty",
    ## "56.7": "Indicate the extent you have felt this way over the past week. Scared",
    ## "56.8": "Indicate the extent you have felt this way over the past week. Hostile",
    ## "56.9": "Indicate the extent you have felt this way over the past week. Enthusiastic",
    ## "56.10": "Indicate the extent you have felt this way over the past week. Proud",
    ## "56.11": "Indicate the extent you have felt this way over the past week. Irritable",
    ## "56.12": "Indicate the extent you have felt this way over the past week. Alert",
    ## "56.13": "Indicate the extent you have felt this way over the past week. Ashamed",
    ## "56.14": "Indicate the extent you have felt this way over the past week. Inspired",
    ## "56.15": "Indicate the extent you have felt this way over the past week. Nervous",
    ## "56.16": "Indicate the extent you have felt this way over the past week. Determined",
    ## "56.17": "Indicate the extent you have felt this way over the past week. Attentive",
    ## "56.18": "Indicate the extent you have felt this way over the past week. Jittery",
    ## "56.19": "Indicate the extent you have felt this way over the past week. Active",
    ## "56.20": "Indicate the extent you have felt this way over the past week. Afraid",
}

belgrade_q_dct = {
    "Molimo Vas, da od navedena tri parka odaberete onaj koji ćete kao učesnik u studiji posećivati u naredna tri meseca:": "Please choose the park you are going to visit in the next three months",
    "Da li ste ikada posetili gore odabrani park?": "Have you ever visited the demo site?",
    "Koliko vam obično vremena treba da stignete do gore odabranog parka? Molimo Vas, zaokružite jedan odgovor koji najviše odgovara utrošku vremena da do njega stignete.": "How long does it take to get to the demo site?",
    "U većini aspekata moj život je blizu idealnog.": "In most ways my life is close to my ideal",
    "Moji uslovi života su odlični": "The conditions of my life are excellent",
    "Zadovoljan/na sam svojim životom.": "I am satisfied with my life",
    "Do sada imam sve važne stvari koje sam želeo/la u životu.": "So far I have gotten the important things I want in life",
    "Da mogu da živim svoj život ponovo, ne bih menjao/la skoro ništa.": "If I could live my life over, I would change almost nothing",
    "Molimo Vas da na na osnovu Vašeg iskustva ocenite kvalitet poseta gore navedenom parku na skali od 1 do 7 ocenite. Pod kvalitetom iskustva podrazumevamo Vaš utisak o lepoti i čistoći lokacije, kao i čulni doživljaj": "Quality of experience",
    "Osećam optimizam u pogledu budućnosti": "I've been feeling optimistic about the future",
    "Osećam se korisno": "I've been feeling useful",
    "Osećam se opušteno": "I've been feeling relaxed",
    "Dobro sam rešavao/la probleme": "I've been dealing with problems well",
    "Razmišljao/la sam jasno": "I've been thinkign clearly",
    "Osećam bliskost sa drugim ljudima": "I've been feeling close to other people",
    "Uspeo/la sam da odlučim o nekim stvarima": "I've been able to make up my own mind about things",
    "Koliko često osećate da vam nedostaje druženje?": "How often do you feel that you lack companionship?",
    "18.	Koliko imate godina:": "Age",
    "19.	Pol:": "Sex",
    "20.	Kako biste definisali svoj rodni identitet?": "Gender",
    ## "Da li u vašoj okolini imate pristup sledećim uslugama? Molimo vas, odaberite svaku kojoj imate pristup.": "Do you have access in your neighbourghood to the following services?",
    "Koliko često se osećate napuštenim?": "How often do you feel left out?",
    "Koliko često se osećate izolovanim od drugih?": "How often do you feel isolated from other people?",
    ##    "Crveno meso": "How often do you eat? Red meat",
    ##    "Belo meso": "How often do you eat? Red meat",
    ##    "Riba ili plodovi mora": "How often do you eat? Fish and sea food",
    ##    "Mesne prerađevine": "How often do you eat? Processed meat",
    ##    "Mleko i/ili mlečni proizvodi": "How often do you eat? Milk and/or dairy products",
    ##    "Voće (uključujući smrznuto, konzervirano ili drugo)": "How often do you eat? Fruits (including frozen, canned and other fruit)",
    ##    "Povrće ( izuzimajući krompir)": "How often do you eat? Vegetables (excluding potatos)",
    ##    "Slatkiši (uključujući torte, kolače, bombone, čokoladu, puding, itd.)": "How often do you eat? Sweets (including cakes, candies, chocolate, pudding, etc.)",
    ##    "Zaslađena bezalkoholna pića (npr: coca-cola, ledeni čaj itd.)": "How often do you eat? Sweetened non-alcoholic beverages (e.g., coca-cola, ice-tea, etc.)",
    ##    "Brza hrana (npr. pica, hamburger, pomfrit,)": "How often do you eat? Fast food (e.g., pizza, hamburgers, french fries, any national fast food)",
    ##    "Beli hleb": "How often do you eat? White bread",
    ##    "Hleb od celog zrna": "How often do you eat? Wholegrain bread",
}

athens_q_dct = {
    "Πρώτα θα θέλαμε να σας κάνουμε ερωτήσεις σχετικά με τις επισκέψεις σας στο Πεδίον του Άρεως και τη γενική εμπειρία σας με τον χώρο. Έχετε επισκεφθεί ποτέ το Πεδίον του Άρεως;": "Have you ever visited the demo site?",
    "18.	Ποια είναι η ηλικία σας:": "Age",
    "19.	Ποιο είναι το φύλο σας:": "Sex",
    "20.	Πώς θα περιγράφατε την ταυτότητα φύλου σας; Επιλέξτε μόνο μία απάντηση": "Gender",
}

aarhus_q_dct = {
    "Først vil vi gerne stille dig spørgsmål vedrørende dine besøg på MarselisborgCentret og din generelle oplevelse med parken. Har du nogensinde besøgt MarselisborgCentret?": "Have you ever visited the demo site?"
}
